Calculator OOP
Zhora1337/external-courses pull request #16
Opened 2018-11-29 17:16 UTC by Zhora1337

Created engeneeric and triganometric calculators.

2018-11-29 19:12 UTC, eugrdn requested changes

2018-11-29 19:12 UTC, eugrdn commented on src/ex15_js-oop/calculator.js
> +    this.type = "Engeneering Calculator";
`type` и `result` ты объявляешь в каждом классе, хотя они являются наследниками Calculator

переиспользуй конструктор

2018-11-29 19:12 UTC, eugrdn commented on src/ex15_js-oop/calculator.js
> +EngeneeringCalculator.prototype = Object.create(Calculator.prototype);
не сохраняешь свойство `constructor`  + TriganometricCalculator

2018-11-29 19:12 UTC, eugrdn commented on src/ex15_js-oop/calculator.js
> +EngeneeringCalculator.prototype.sqrt = function() {
почему без аргументов?

2018-11-29 19:12 UTC, eugrdn commented on src/ex15_js-oop/calculator.js
> +    console.log (Math.cos(this.result * 180 / Math.PI));
аналогично про методы `get...`, как в https://github.com/Zhora1337/external-courses/pull/15

2018-11-30 12:45 UTC, Zhora1337 commented on src/ex15_js-oop/calculator.js
> +EngeneeringCalculator.prototype.sqrt = function() {
квадратный корень от текущего значения свойства result, операция проводится только над ним, других операндов нет

2018-12-01 08:47 UTC, eugrdn approved these changes

2018-12-01 08:47 UTC, merged